[world]
name = "witch_or_treat"
description = "A Halloween Treat Gathering Game"
seed = "witch_or_treat_v1"

[namespace]
default = "witch_or_treat"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x01ae818d58b6d6821cdabc73f8fb0d79b68190177061390edaf14f78484b82f6"

[writers]
"witch_or_treat" = ["witch_or_treat-actions"]
