[package]
cairo-version = "2.12.2"
name = "witch_or_treat"
version = "1.7.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.12.2"
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.0"
